### ISSUE TITLE
Custom SPI setting

### ISSUE THREAD

**Issue by williamesp2015** [baldram/ESP_VS1053_Library#17]
I am using Arduino MP3 Sheild (http://www.geeetech.com/wiki/index.php/Arduino_MP3_shield_board_with_TF_card)
using arduino-esp32. I connected VS1053_CS,VS1053_DCS,VS1053_DREQ,CLK,MISO,MOSI, GND, +5 V
It had problem with LOG and I changed to Serial.print & printf then it started. I connected headphone and also computer speaker but noting can hear.
#define VS1053_CS     32//5
#define VS1053_DCS    33//16
#define VS1053_DREQ   27//4 DREQ is an input
#define CLK 16      // SPI Clock
#define MISO 17      // Input data from VS1053 card
....
  SPI.begin(SCK,MISO,MOSI);//,CS);
    delay(10);
    // initialize SPI
  //  SPI.begin();
OUTPUT:
Hello VS1053!

Reset VS1053...
End reset VS1053...
Slow SPI,Testing VS1053 read/write registers...
VS1053 error retry SB:0000 R1:FFFF  R2:FFFF
VS1053 error retry SB:012C R1:FFFF  R2:FFFF
VS1053 error retry SB:0708 R1:FFFF  R2:FFFF
VS1053 error retry SB:0834 R1:FFFF  R2:FFFF
VS1053 error retry SB:0960 R1:FFFF  R2:FFFF
VS1053 error retry SB:0A8C R1:FFFF  R2:FFFF
VS1053 error retry SB:0BB8 R1:FFFF  R2:FFFF
VS1053 error retry SB:0CE4 R1:FFFF  R2:FFFF
VS1053 error retry SB:0E10 R1:FFFF  R2:FFFF
VS1053 error retry SB:0F3C R1:FFFF  R2:FFFF
VS1053 error retry SB:1068 R1:FFFF  R2:FFFF
VS1053 error retry SB:1068 R1:FFFF  R2:FFFF
VS1053 error retry SB:1194 R1:FFFF  R2:FFFF
VS1053 error retry SB:12C0 R1:FFFF  R2:FFFF
VS1053 error retry SB:13EC R1:FFFF  R2:FFFF
VS1053 error retry SB:1518 R1:FFFF  R2:FFFF
VS1053 error retry SB:1644 R1:FFFF  R2:FFFF
Switched to mp3 mode
Performing soft-reset
Playing sound...
Playing sound...
Playing sound...

Please advice how to convert my own MP3 file to C header file. Thank you

**Comment by baldram** [comment]
Hi @williamesp2015 I see you opened an issue and further it was closed.
So if you managed to run the library with your hardware, I would be glad if you add a comment to this thread: https://github.com/baldram/ESP_VS1053_Library/issues/1 about the hardware you use and how everything is connected/configured. 
I collect information about the hardware which was tested with this library.

As you see here, by experimenting, I managed to run the library with ESP32 board. By experimenting the wiring is as described here:  https://github.com/baldram/ESP_VS1053_Library/issues/1#issuecomment-313907348
I guess it should be something similar in your case. But maybe some pins are different and they should b configured in your .ino sketch file accordingly. So I guess you successfully configured everything and it would be nice if you add a description to ["To test the library with different hardware"](https://github.com/baldram/ESP_VS1053_Library/issues/1) thread.
