### ISSUE TITLE
How to read mp3 file on sd card ?

### ISSUE THREAD

**Issue by hoahoctro** [baldram/ESP_VS1053_Library#58]
I made many searchs and couldnt find any lib supports this feature, hope you can help

**Comment by baldram** [comment]
Hi this is not relevant to this project. The driver is not dealing with SD card, but with Audio device. 
Please have a look in PlatformIO library search: https://platformio.org/lib/search?query=platform%253A%2522espressif8266%2522%2520SD&page=1 .
