### ISSUE TITLE
setVolume values / question

### ISSUE THREAD

**Issue by h1aji** [baldram/ESP_VS1053_Library#85]
I was comparing **setVolume**

https://github.com/baldram/ESP_VS1053_Library/blob/f501eb734f0517f2c079369024201667c6471fee/src/VS1053.cpp#L189-L218

with the [code from Adafruit](https://github.com/adafruit/Adafruit_VS1053_Library/blob/aedb7bbce6e83acb5e48ce7a93e10d3a5afe3bf0/Adafruit_VS1053.cpp#L459)

```
void Adafruit_VS1053::setVolume(uint8_t left, uint8_t right) {
  // accepts values between 0 and 255 for left and right.
  uint16_t v;
  v = left;
  v <<= 8;
  v |= right;

  noInterrupts(); // cli();
  sciWrite(VS1053_REG_VOLUME, v);
  interrupts(); // sei();
}
```

And found that maximum value for setVolume is 254. So, which value would be correct in this case?

**Comment by Dr-Dawg** [comment]
The map function maps the values from 0-100 to 0-254  (= 0xFE ), see
https://www.arduino.cc/reference/de/language/functions/math/map/
So basically both funtions do the same. Using a range from 0-100 is of course coarser, but imho is more intuitive and does not really make a difference.
