### ISSUE TITLE
webradio: how to listen aac streaming ?

### ISSUE THREAD

**Issue by philippedc** [baldram/ESP_VS1053_Library#93]
Hi, for me, the webradio example works fine for mpeg or mp3 stations. For instance:
http://icecast.radiofrance.fr/francemusique-midfi.mp3
http://149.255.59.3:8029/stream

but for any aac radio station I do not get any audio:
http://icecast.radiofrance.fr/francemusique-lofi.aac
http://radioseribatu.out.airtime.pro:8000/radioseribatu_a

what must I do ? Should I use an ESP32 instead of the ESP8266 ?

I have another question:
https://mikadofm.minusma.unmissions.org:8001/feed1
I'm wondering how to understand the port number... in the code it does not work neither with 443 nor 8001

**Comment by Dr-Dawg** [comment]
I think the reason for the first link could be you're using a VS1003 which does not support aac.
If you are using the latest library you can check by something like
```
    if (player.getChipVersion() == 4) { 
        Serial.println("VS1053 - aac");
    }
else
        Serial.println("VS1003 - no aac");
```

For the second link, I think https is the reason.  So far I never got a https stream to work..
